spring:
  output:
    ansi:
      enabled: always
  datasource:
      url: jdbc:mysql://localhost:3306/deviceman_db?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
